const defaultCity = {
  "by": "default",
  "valid_key": false,
  "results": {
    "temp": 22,
    "date": "14/11/2023",
    "time": "21:12",
    "condition_code": "28",
    "description": "Tempo nublado",
    "currently": "noite",
    "cid": "",
    "city": "São Paulo, SP",
    "img_id": "28n",
    "humidity": 90,
    "cloudiness": 75.0,
    "rain": 0.0,
    "wind_speedy": "6.69 km/h",
    "wind_direction": 180,
    "wind_cardinal": "S",
    "sunrise": "05:14 am",
    "sunset": "06:27 pm",
    "moon_phase": "waxing_crescent",
    "condition_slug": "cloudly_night",
    "city_name": "São Paulo",
    "timezone": "-03:00",
    "forecast": [
      {
        "date": "14/11",
        "weekday": "Ter",
        "max": 37,
        "min": 22,
        "cloudiness": 3.0,
        "rain": 0.0,
        "rain_probability": 22,
        "wind_speedy": "7.17 km/h",
        "description": "Tempo limpo",
        "condition": "clear_day"
      },
      {
        "date": "15/11",
        "weekday": "Qua",
        "max": 38,
        "min": 21,
        "cloudiness": 0.0,
        "rain": 0.11,
        "rain_probability": 24,
        "wind_speedy": "4.93 km/h",
        "description": "Chuvas esparsas",
        "condition": "rain"
      },
      {
        "date": "16/11",
        "weekday": "Qui",
        "max": 39,
        "min": 23,
        "cloudiness": 100.0,
        "rain": 0.0,
        "rain_probability": 1,
        "wind_speedy": "7.44 km/h",
        "description": "Tempo nublado",
        "condition": "cloudly_day"
      },
      {
        "date": "17/11",
        "weekday": "Sex",
        "max": 37,
        "min": 22,
        "cloudiness": 100.0,
        "rain": 0.0,
        "rain_probability": 14,
        "wind_speedy": "6.56 km/h",
        "description": "Tempo nublado",
        "condition": "cloudly_day"
      },
      {
        "date": "18/11",
        "weekday": "Sáb",
        "max": 25,
        "min": 22,
        "cloudiness": 100.0,
        "rain": 1.05,
        "rain_probability": 25,
        "wind_speedy": "6.17 km/h",
        "description": "Chuvas esparsas",
        "condition": "rain"
      },
      {
        "date": "19/11",
        "weekday": "Dom",
        "max": 22,
        "min": 21,
        "cloudiness": 100.0,
        "rain": 8.5,
        "rain_probability": 100,
        "wind_speedy": "5.27 km/h",
        "description": "Chuvas esparsas",
        "condition": "rain"
      },
      {
        "date": "20/11",
        "weekday": "Seg",
        "max": 28,
        "min": 18,
        "cloudiness": 100.0,
        "rain": 12.09,
        "rain_probability": 100,
        "wind_speedy": "8.25 km/h",
        "description": "Chuva",
        "condition": "rain"
      },
      {
        "date": "21/11",
        "weekday": "Ter",
        "max": 22,
        "min": 17,
        "cloudiness": 86.0,
        "rain": 4.23,
        "rain_probability": 100,
        "wind_speedy": "4.34 km/h",
        "description": "Chuvas esparsas",
        "condition": "rain"
      },
      {
        "date": "22/11",
        "weekday": "Qua",
        "max": 28,
        "min": 18,
        "cloudiness": 39.0,
        "rain": 1.45,
        "rain_probability": 55,
        "wind_speedy": "4.34 km/h",
        "description": "Chuvas esparsas",
        "condition": "rain"
      },
      {
        "date": "23/11",
        "weekday": "Qui",
        "max": 28,
        "min": 19,
        "cloudiness": 100.0,
        "rain": 10.9,
        "rain_probability": 100,
        "wind_speedy": "5.88 km/h",
        "description": "Chuva",
        "condition": "rain"
      }
    ],
    "cref": "0a01c8"
  },
  "execution_time": 0.0,
  "from_cache": true
}

export default defaultCity;