const city = {
  city: 'Itapema, SC',
  temp: 25,
  date: '5/11/2023',
  rain: 0.0,
  currently: 'noite',
  description: "Chuvas esparsas",
  humidity: 75,
  "time": "16:07",
  cloudiness: 10,
  wind_speedy: "2.24 km/h",
  condition: 'clear_day',
  moon_phase: 'first_quarter',
  sunrise: "05:18 am",
  sunset: "06:38 pm",
  forecast: [
    {
      "date": "09/11",
      "weekday": "Qui",
      "max": 25,
      "min": 19,
      "cloudiness": 100.0,
      "rain": 2.04,
      "rain_probability": 70,
      "wind_speedy": "5.07 km/h",
      "description": "Chuvas esparsas",
      "condition": "rain"
    },
    {
      "date": "10/11",
      "weekday": "Sex",
      "max": 22,
      "min": 20,
      "cloudiness": 100.0,
      "rain": 1.87,
      "rain_probability": 55,
      "wind_speedy": "3.14 km/h",
      "description": "Chuvas esparsas",
      "condition": "rain"
    },
    {
      "date": "11/11",
      "weekday": "Sáb",
      "max": 27,
      "min": 21,
      "cloudiness": 67.0,
      "rain": 2.07,
      "rain_probability": 91,
      "wind_speedy": "4.75 km/h",
      "description": "Chuvas esparsas",
      "condition": "rain"
    },
    {
      "date": "12/11",
      "weekday": "Dom",
      "max": 27,
      "min": 21,
      "cloudiness": 77.0,
      "rain": 0.32,
      "rain_probability": 39,
      "wind_speedy": "4.57 km/h",
      "description": "Chuvas esparsas",
      "condition": "rain"
    },
    {
      "date": "13/11",
      "weekday": "Seg",
      "max": 26,
      "min": 21,
      "cloudiness": 100.0,
      "rain": 2.62,
      "rain_probability": 80,
      "wind_speedy": "4.4 km/h",
      "description": "Chuvas esparsas",
      "condition": "rain"
    },
    {
      "date": "14/11",
      "weekday": "Ter",
      "max": 24,
      "min": 21,
      "cloudiness": 99.0,
      "rain": 8.57,
      "rain_probability": 100,
      "wind_speedy": "4.87 km/h",
      "description": "Chuva",
      "condition": "rain"
    },
    {
      "date": "15/11",
      "weekday": "Qua",
      "max": 23,
      "min": 21,
      "cloudiness": 100.0,
      "rain": 2.37,
      "rain_probability": 84,
      "wind_speedy": "3.48 km/h",
      "description": "Chuvas esparsas",
      "condition": "rain"
    },
    {
      "date": "16/11",
      "weekday": "Qui",
      "max": 26,
      "min": 21,
      "cloudiness": 100.0,
      "rain": 11.55,
      "rain_probability": 100,
      "wind_speedy": "6.38 km/h",
      "description": "Chuva",
      "condition": "rain"
    },
    {
      "date": "17/11",
      "weekday": "Sex",
      "max": 26,
      "min": 21,
      "cloudiness": 94.0,
      "rain": 5.47,
      "rain_probability": 92,
      "wind_speedy": "3.77 km/h",
      "description": "Chuva",
      "condition": "rain"
    },
    {
      "date": "18/11",
      "weekday": "Sáb",
      "max": 27,
      "min": 21,
      "cloudiness": 100.0,
      "rain": 8.84,
      "rain_probability": 100,
      "wind_speedy": "4.47 km/h",
      "description": "Chuva",
      "condition": "rain"
    }
  ],
}

export default city;